### ISSUE TITLE
Function isn't working properly

### ISSUE THREAD

**Issue by Jaynob-Binte-Sayed** [Virtual-Haat/google-ads-display#12]
I have declared a function earlier and it had only one line of code that says to display an element as an inline element.
Due to the need of my project, I have added another line of code that works exactly the same as the previous one but it will display the new element as a block. 
Whenever the function is executed, I am getting the below attached error.
![image](https://github.com/Virtual-Haat/google-ads-display/assets/94732549/f703befd-17c4-4118-823e-ae508566f08b)

The function is attached here.
![image](https://github.com/Virtual-Haat/google-ads-display/assets/94732549/7737a31e-73f0-427f-a704-a26da89e0167)

For more clearance, I am attaching the blocks where this function been added and used.
![image](https://github.com/Virtual-Haat/google-ads-display/assets/94732549/553fac17-530c-431d-bb99-f5b6e88b4e57)
![image](https://github.com/Virtual-Haat/google-ads-display/assets/94732549/86982782-b21e-4224-a286-7d7c78061e90)

To provide a back story:
I though of wrapping the p tag with a div tag. But as I was getting the error. I have commented out the div tag and only used p tag.

**In case you want to review my style codes too, please let me know.

**Comment by Prodip007** [comment]
I am working on this issue @Jaynob-Binte-Sayed

**Comment by Prodip007** [comment]
The "id" you declared on the function was not attached to any html element. I think this bug is now fixed.
