### ISSUE TITLE
problem in "src/components/AdPrivew.vue"

### ISSUE THREAD

**Issue by Prodip007** [Virtual-Haat/google-ads-display#8]
Please, fix the error bellow. @Jaynob-Binte-Sayed 

![image](https://github.com/Virtual-Haat/google-ads-display/assets/54480254/97d3ae58-56e6-4c93-891b-23c368db53c0)

**Comment by Jaynob-Binte-Sayed** [comment]
Checking this out.

**Comment by Prodip007** [comment]
@Jaynob-Binte-Sayed  please update this issue!!

**Comment by Jaynob-Binte-Sayed** [comment]
As the issue has been solved, I would request you to close it.
